{
 "title": "Garage",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(garage_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "table_gc_todo_queue_length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "table_gc_todo_queue_length{instance=\"$instance\"}",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "S3 methods per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(api_s3_request_counter{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{api_endpoint}}"
    }
   ]
  },
  {
   "title": "RPC duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(rpc_duration_bucket{job=\"garage_nodes\", instance=\"$instance\"}[$__rate_interval])) by (le, rpc_endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block resync rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(block_resync_counter[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(rpc_request_counter{job=\"garage_nodes\", instance=\"$instance\" }[$__rate_interval])",
     "legendFormat": "{{rpc_endpoint}}"
    }
   ]
  },
  {
   "title": "S3 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(api_s3_error_counter[$__rate_interval]) ",
     "legendFormat": "{{instance}} {{api_endpoint}} {{status_code}}"
    }
   ]
  },
  {
   "title": "block_resync_queue_length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "block_resync_queue_length", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "S3 requests duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_s3_request_duration_bucket{instance=\"$instance\"}[$__rate_interval])) by (le, api_endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 33 },
   "targets": [
    { "expr": "garage_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Factor",
   "type": "stat",
   "gridPos": { "h": 7, "w": 1, "x": 3, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "garage_replication_factor{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "api_admin_request_counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 33 },
   "targets": [
    {
     "expr": "rate(api_admin_request_counter[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "block_resync_errors (should be zero)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 33 },
   "targets": [
    {
     "expr": "block_resync_errored_blocks > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC timeouts (should be 0)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 33 },
   "targets": [
    {
     "expr": "rate(rpc_timeout_counter[$__rate_interval]) > 0",
     "legendFormat": "{{instance}} {{rpc_endpoint}}"
    }
   ]
  },
  {
   "title": "Table size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 33 },
   "targets": [
    {
     "expr": "table_size{job=\"garage_nodes\", instance=\"$instance\"}",
     "legendFormat": "{{table_name}}"
    }
   ]
  }
 ]
}