---
kind: pipeline
name: default

workspace:
  base: /drone/garage

volumes:
- name: cargo_home
  temp: {}

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    volumes:
    - name: cargo_home
      path: /drone/cargo
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: cache_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_aws_secret_access_key
    pull: true
    settings:
      restore: true
      archive_format: "gzip"
      bucket: drone-cache
      cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}_gzip'
      region: garage
      mount:
        - '/drone/cargo'
        - 'target'
      path_style: true
      endpoint: https://garage.deuxfleurs.fr
    when:
      branch:
      - nonexistent_skip_this_step

  - name: code quality
    image: superboum/garage_builder_amd64:4
    volumes:
    - name: cargo_home
      path: /drone/cargo
    environment:
      CARGO_HOME: /drone/cargo
    commands:
      - cargo fmt -- --check
      - cargo clippy -- --deny warnings

  - name: build
    image: superboum/garage_builder_amd64:4
    volumes:
    - name: cargo_home
      path: /drone/cargo
    environment:
      CARGO_HOME: /drone/cargo
    commands:
      - pwd
      - cargo build

  - name: cargo-test
    image: superboum/garage_builder_amd64:4
    volumes:
    - name: cargo_home
      path: /drone/cargo
    environment:
      CARGO_HOME: /drone/cargo
    commands:
      - cargo test

  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    volumes:
    - name: cargo_home
      path: /drone/cargo
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: cache_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_aws_secret_access_key
    pull: true
    settings:
      rebuild: true
      archive_format: "gzip"
      bucket: drone-cache
      cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}_gzip'
      region: garage
      mount:
        - '/drone/cargo'
        - 'target'
      path_style: true
      endpoint: https://garage.deuxfleurs.fr
    when:
      branch:
      - nonexistent_skip_this_step

  - name: smoke-test
    image: superboum/garage_builder_amd64:4
    volumes:
    - name: cargo_home
      path: /drone/cargo
    environment:
      CARGO_HOME: /drone/cargo
    commands:
      - ./script/test-smoke.sh || (cat /tmp/garage.log; false)

---
kind: pipeline
name: website

steps:
  - name: build
    image: hrektts/mdbook
    commands:
      - cd doc/book
      - mdbook build

  - name: upload
    image: plugins/s3
    settings:
      bucket: garagehq.deuxfleurs.fr
      access_key:
        from_secret: garagehq_aws_access_key_id
      secret_key:
        from_secret: garagehq_aws_secret_access_key
      source: doc/book/book/**/*
      strip_prefix: doc/book/book/
      target: /
      path_style: true
      endpoint: https://garage.deuxfleurs.fr
      region: garage
    when:
      event:
        - push
      branch:
        - main
      repo:
        - Deuxfleurs/garage

---
kind: signature
hmac: e919f8a66d20ebfeeec56b291a8a0fdd59a482601da987fcf533d96d24768744

...
