[workspace]
members = [
	"src/util",
	"src/rpc",
	"src/table",
	"src/block",
	"src/model",
	"src/admin",
	"src/api",
	"src/web",
	"src/garage",
	"src/k2v-client",
]

default-members = ["src/garage"]

[profile.dev]
lto = "off"

[profile.release]
debug = true
