[package]
name = "k2v-client"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
http = "0.2.6"
rusoto_core = "0.48.0"
rusoto_credential = "0.48.0"
rusoto_signature = "0.48.0"
serde = "1.0.137"
serde_json = "1.0.81"
thiserror = "1.0.31"
tokio = "1.17.0"
